### PR TITLE
Model Working in Ersilia.

### PR DESCRIPTION
**Pull request by samuelmaina**
Incorporated the model with ersilia cli and its working fine.

### CODE REVIEW

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 

Please revise the tests and amend the metadata file

**Comment by samuelmaina** [comment]
Right away.

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 

I've reopened the PR
I won't be able to merge it until our Git LFS quota is solved, someone has been extremely active in downloading a couple of repositories particularly large, sorry

**Comment by samuelmaina** [comment]
@GemmaTuron , I deleted the previous fork  to get a new Git LFS quota  in a new fork repo. I did not know the problem was on ersilia end. You can notify me when the problem is resolved.

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 

Yes, the git lfs is depending on Ersilia - we will wait until it is reseted in 10 days to limit the expenditure we have. 
Please leave the PR and your fork open until then and I'll merge the changes at that time

**Comment by samuelmaina** [comment]
Deleting the fork deleted the updated commits. Cloning the repo throws the LFS error hence I can't commit new changes. I will update with the new code after 10 days.

**Comment by GemmaTuron** [comment]
Hi  @samuelmaina 

I've solved the git lfs issue for the moment, please go ahead and finish the model ;)

**Comment by samuelmaina** [comment]
Okay. Working on it now

**Comment by samuelmaina** [comment]
@GemmaTuron  have a look at  PR [https://github.com/ersilia-os/eos6aun/pull/2](https://github.com/ersilia-os/eos6aun/pull/2) .

**Pull request closed without merging**
