### PR TITLE
Corrected the metadata and the return type

### PR DESCRIPTION
**Pull request by samuelmaina**
Corrected a comma in metadata and changed the  return type to  string

### CODE REVIEW

**Comment by samuelmaina** [comment]
@GemmaTuron working on this on the failing tests. My description was short but I will be careful next time.

**Comment by samuelmaina** [comment]
I have seen you have added more  description. thanks.

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 

You had also deleted input shape for instance, and some fields did not use the established rules
I've done the edits to be able to test the model, let's see if it passes the test

**Comment by samuelmaina** [comment]
Thanks for the correction. I have reviewed you commit and have seen read the required changes.

**Comment by GemmaTuron** [comment]
HI @samuelmaina !

all checks have passed, congratulations for the first model incorporation!

**Pull request merged**
